getUsers:
    path: /api/admin/users
    controller: App\Controller\PersonneController::getUsers
    methods: ['GET']

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
authentication_token:
    path: /api/login
    methods: ['POST']